apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: product 
