name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Build Docker image
        run: |
          docker build -t my-app .
      
      - name: Run tests
        run: |
          docker run my-app npm test
      
      - name: Push to DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push my-app
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml

    # Use environment variables instead of deprecated set-output/save-state
    steps:
      - name: Set version environment variable
        run: echo "VERSION=v1.0.0" >> $GITHUB_ENV  # Example of setting environment variable

      # Additional example to use version as environment variable
      - name: Print Version
        run: echo "The version is ${{ env.VERSION }}"
